# Generated by Django 2.2.4 on 2020-05-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('job_role', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('job_category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'job_listings',
            },
        ),
    ]
