# Generated by Django 2.2.4 on 2020-05-30 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zeroxpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistings',
            name='job_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblistings',
            name='job_posted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblistings',
            name='skills',
            field=models.TextField(default='python'),
            preserve_default=False,
        ),
    ]
