# Generated by Django 2.2.4 on 2020-05-31 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroxpapp', '0002_auto_20200530_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblistings',
            name='job_posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
