# Generated by Django 2.2.4 on 2020-06-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroxpapp', '0004_emailleads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailleads',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
